### ISSUE TITLE
Add meta description tags to pages

### ISSUE THREAD

**Issue by despawnerer** [despawnerer/theatrics#30]
- [ ] Initial meta on main page: "Театральная афиша: спектакли и все такое."
- [ ] Event list: names of first three events
- [ ] Place list: names of first three places
- [ ] Place: short description
- [ ] Event: short description
